const grpc = require('@grpc/grpc-js');
const { connect, signers } = require('@hyperledger/fabric-gateway');
const crypto = require('crypto');
const fs = require('fs/promises');
const path = require('path');

const channelName = 'remittancechannel';
const chaincodeName = 'remittance';

// Paths to the crypto materials generated by test-network
const cryptoPath = path.resolve(__dirname, '../fabric-samples', 'test-network', 'organizations', 'peerOrganizations', 'org1.example.com');
const certPath = path.resolve(cryptoPath, 'users', 'User1@org1.example.com', 'msp', 'signcerts', 'cert.pem');
const keyDirectoryPath = path.resolve(cryptoPath, 'users', 'User1@org1.example.com', 'msp', 'keystore');
const tlsCertPath = path.resolve(cryptoPath, 'peers', 'peer0.org1.example.com', 'tls', 'ca.crt');
const peerEndpoint = 'localhost:7051';

async function newGrpcConnection() {
    const tlsRootCert = await fs.readFile(tlsCertPath);
    const tlsCredentials = grpc.credentials.createSsl(tlsRootCert);
    return new grpc.Client(peerEndpoint, tlsCredentials, {
        'grpc.ssl_target_name_override': 'peer0.org1.example.com'
    });
}

async function newIdentity() {
    const credentials = await fs.readFile(certPath);
    return { mspId: 'Org1MSP', credentials };
}

async function newSigner() {
    const files = await fs.readdir(keyDirectoryPath);
    const keyPath = path.resolve(keyDirectoryPath, files[0]);
    const privateKeyPem = await fs.readFile(keyPath);
    const privateKey = crypto.createPrivateKey(privateKeyPem);
    return signers.newPrivateKeySigner(privateKey);
}

// 1. Function to Submit a Transaction (Writes to Ledger)
async function submitRemittance(txId, senderId, receiverId, amountUSD) {
    const client = await newGrpcConnection();
    const gateway = connect({ client, identity: await newIdentity(), signer: await newSigner() });

    try {
        const network = gateway.getNetwork(channelName);
        const contract = network.getContract(chaincodeName);
        
        console.log(`\n--> Blockchain Submit: ProcessRemittance ${txId}`);
        await contract.submitTransaction('ProcessRemittance', txId, senderId, receiverId, amountUSD.toString());
        console.log('*** Transaction committed successfully!');
        return { status: "success" };
    } catch (error) {
        console.error('*** Blockchain Rejected Transaction:', error.message);
        throw error;
    } finally {
        gateway.close();
        client.close();
    }
}

// 2. Function to Query a Participant (Reads from Ledger)
async function queryParticipant(participantId) {
    const client = await newGrpcConnection();
    const gateway = connect({ client, identity: await newIdentity(), signer: await newSigner() });

    try {
        const network = gateway.getNetwork(channelName);
        const contract = network.getContract(chaincodeName);
        
        console.log(`\n--> Blockchain Evaluate: QueryParticipant ${participantId}`);
        const resultBytes = await contract.evaluateTransaction('QueryParticipant', participantId);
        const resultJson = new TextDecoder().decode(resultBytes);
        return JSON.parse(resultJson);
    } catch (error) {
        console.error(`*** Failed to query participant ${participantId}:`, error.message);
        throw error;
    } finally {
        gateway.close();
        client.close();
    }
}

async function getAllTransactions() {
    const client = await newGrpcConnection();
    const gateway = connect({ client, identity: await newIdentity(), signer: await newSigner() });

    try {
        const network = gateway.getNetwork(channelName);
        const contract = network.getContract(chaincodeName);
        
        const resultBytes = await contract.evaluateTransaction('GetAllTransactions');
        const resultJson = new TextDecoder().decode(resultBytes);
        return JSON.parse(resultJson);
    } finally {
        gateway.close();
        client.close();
    }
}
module.exports = { submitRemittance, queryParticipant, getAllTransactions };